stages:
  data_ingestion:
    cmd: python src/cnnClassifier_Eye/pipeline/stage_01_data_ingeation.py
    deps:
      - src/cnnClassifier_Eye/pipeline/stage_01_data_ingeation.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/train 
      - artifacts/data_ingestion/test


  prepare_base_model:
    cmd: python src/cnnClassifier_Eye/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier_Eye/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
      - model_name
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier_Eye/pipeline/stage_03_model_train.py
    deps:
      - src/cnnClassifier_Eye/pipeline/stage_03_model_train.py
      - config/config.yaml
      - artifacts/data_ingestion/train
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier_Eye/pipeline/stage_04_model_evaluation.py
    deps:
      - src/cnnClassifier_Eye/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/train
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false